server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CollaTime
    username: ohgiraffers
    password: ohgiraffers

## MyBatis config
mybatis:
  mapper-locations: mapper/**/*.xml
